version: 2
jobs:
    gtest:
        working_directory: ~/root
        docker:
            - image: gcc:latest
        steps:
            - run:
                name: Downloading dependencies
                command: |
                    apt-get update
                    apt-get install -y cmake
                    apt-get install -y libgtest-dev
            - run:
                name: Installing dependencies
                working_directory: /usr/src/gtest/
                command: |
                    cmake CMakeLists.txt
                    make
                    cp /usr/src/gtest/*.a /usr/lib
            - checkout
            - run:
                name: "Pull Submodules"
                command: |
                    git submodule init
                    git submodule update --recursive --remote
            - run:
                name: Building tests
                command: make gtests
            - run:
                name: Running tests
                command: ./GTests --gtest_filter=*
workflows:
    version: 2
    build_and_test:
        jobs:
            - gtest:
                filters:
                    branches:
                        only:
                            - master
                            - develop
                            - tests